paypal:
  client-id: AagEoPfJ0Y63HCipdG9J3sjdKlG-Q5rQlU_7dlACPe5InrBWK3YtMskKyasT39HfXk4tbkWCwANxTey7
  client-secret: EFPCrSy0KTgYtwJFVu-eGKdTEY5RHQbz8qT90g8wcIj-yDJsLRwxeJOhm_p4bTuP2NyZh0oEUfI7GUQB
  mode: sandbox